name: Build

on:
  push:
    branches:
      - '!main'   # excludes master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/gradlew
        id: gradlew

      - run: echo "Built ${{ steps.gradlew.outputs.jar_file }}"
