name: Build

on:
  push:
    branches:
      - '**'      # all branches
      - '!main'   # except main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/gradlew
        id: gradlew

      - run: echo "Built ${{ steps.gradlew.outputs.jar_file }}"
