name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip on release, but run after the release when bumping to the next SNAPSHOT version
    if: |
      !startsWith(github.event.head_commit.message, 'chore(main): release') || contains(github.event.head_commit.message, 'SNAPSHOT')

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/gradlew
        id: gradlew

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: ${{ steps.gradlew.outputs.jar_file }}

      - name: Deploy to Github Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build/web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update nightly release
        if: success()
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.gradlew.outputs.jar_file }}
